# Generated by Django 4.2.4 on 2023-08-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("telegram_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashSaving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saving_type",
                    models.CharField(
                        choices=[
                            ("Bank Accounts", "Bankaccounts"),
                            ("Term Deposits", "Termdeposits"),
                            ("Securities Investments", "Securitiesinvestments"),
                            ("Retirement Savings", "Retirementsavings"),
                            ("Other Investments", "Otherinvestments"),
                            ("Emergency Fund", "Emergencyfund"),
                            ("Education Savings", "Educationsavings"),
                            ("Big Purchase Fund", "Bigpurchasefund"),
                            ("Vacation Fund", "Vacationfund"),
                            ("Targeted Savings", "Vacationfund"),
                        ],
                        max_length=50,
                        verbose_name="Saving Type",
                    ),
                ),
                ("amount", models.FloatField(default=0, verbose_name="savings Amount")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cash_savings",
                        to="telegram_user.telegramuser",
                        verbose_name="Telegram User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Saving",
                "verbose_name_plural": "001. Cash Savings",
            },
        ),
    ]
